-- Initial migration for Puthing Around on Supabase
-- The ancient schema for the cosmic cipher

create table if not exists public.target_codes (
    id integer primary key check (id = 1),
    code text not null,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);

create table if not exists public.winner_settings (
    id integer primary key check (id = 1),
    winner_name text default 'Anonymous',
    updated_at timestamp with time zone default now()
);

-- The secret code is guarded by the elders
-- RLS disabled for target_codes (elders only)

create table if not exists public.code_attempts (
    id bigint generated by default as identity primary key,
    guess text not null,
    was_correct boolean not null default false,
    attempted_at timestamp with time zone default now()
);

-- RLS enabled for code_attempts (all seekers may record)
alter table public.code_attempts enable row level security;

create policy "allow insert attempts"
    on public.code_attempts
    for insert
    to public
    with check (true);

create policy "allow select attempts"
    on public.code_attempts
    for select
    to public
    using (true);

-- Function to verify code (the ancient ritual)
create or replace function public.verify_code(guess text)
returns json
language plpgsql
security definer
as $$
declare
    target text;
    feedback json := '[]'::json;
    guess_chars char[];
    code_chars char[];
    used boolean[];
    i integer;
    j integer;
begin
    select code into target from public.target_codes where id = 1;
    
    if not found then
        return json_build_object('error', 'the cipher sleeps. no key set.');
    end if;

    guess_chars := regexp_split_to_array(lower(trim(guess)), '');
    code_chars := regexp_split_to_array(target, '');
    used := array_fill(false, array[array_length(code_chars, 1)]);

    -- first pass: aligned with cosmos
    for i in 1..array_length(guess_chars, 1) loop
        if i <= array_length(code_chars, 1) and guess_chars[i] = code_chars[i] then
            feedback := feedback || 'correct';
            used[i] := true;
        else
            feedback := feedback || 'absent';
        end if;
    end loop;

    -- second pass: echoes in the void
    for i in 1..array_length(guess_chars, 1) loop
        if feedback->(i-1) = 'absent' then
            for j in 1..array_length(code_chars, 1) loop
                if used[j] = false and guess_chars[i] = code_chars[j] then
                    feedback := (
                        select json_agg(case when idx = i-1 then 'present' else val end)
                        from jsonb_array_elements(feedback) with ordinality
                        as t(val, idx)
                    );
                    used[j] := true;
                    exit;
                end if;
            end loop;
        end if;
    end loop;

    insert into public.code_attempts (guess, was_correct)
    values (lower(trim(guess)), lower(trim(guess)) = target);

    return json_build_object(
        'correct', (lower(trim(guess)) = target),
        'length', array_length(code_chars, 1),
        'feedback', feedback
    );
end;
$$;

-- Function to get statistics
create or replace function public.get_stats()
returns json
language plpgsql
security definer
as $$
begin
    return (
        select json_build_object(
            'total_attempts', count(*),
            'total_solved', coalesce(sum(case when was_correct then 1 else 0 end), 0)::int
        )
        from public.code_attempts
    );
end;
$$;

-- Function to get winner
create or replace function public.get_winner()
returns json
language plpgsql
security definer
as $$
declare
    target_name text;
begin
    select winner_name into target_name from public.winner_settings where id = 1;
    if not found then
        target_name := 'Anonymous';
    end if;
    return json_build_object('winner', target_name);
end;
$$;

create or replace function public.set_winner(name text)
returns json
language plpgsql
security definer
as $$
begin
    insert into public.winner_settings (id, winner_name)
    values (1, name)
    on conflict (id) do update set winner_name = excluded.winner_name;
    return json_build_object('winner', name);
end;
$$;

grant execute on function public.get_winner() to anon;
grant execute on function public.set_winner(text) to anon;

create or replace function public.get_hint()
returns json
language plpgsql
security definer
as $$
declare
    total_attempts bigint;
    hints text[] := array[
        'the path is not on the screen',
        'look where the light does not touch',
        'the first letter is the last letter of the alphabet in reverse',
        'z is not the end',
        'count backwards from z',
        'the answer hides in plain sight',
        'read between the lines',
        'the code is 16 sigils long',
        'throzyckd is not the true code',
        'the cipher whispers: start at the edge'
    ];
    idx int;
begin
    select count(*) into total_attempts from public.code_attempts;
    idx := least(total_attempts, array_length(hints,1));
    return json_build_object('attempts', total_attempts, 'hint', hints[idx], 'level', idx+1);
end;
$$;

grant execute on function public.get_hint() to anon;